import Footer from "@/components/Footer";
import "./globals.css";
import "./style.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: {
    default: "Pranay Surve",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
